# Generated by Django 5.2.17 on 2026-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.FloatField(blank=True, help_text="Durée de l'audio en secondes", null=True),
        ),
    ]
